### ISSUE TITLE
guidance for adding new gateway to shopify

### ISSUE THREAD

**Issue by avenuestest** [activemerchant/offsite_payments#166]
@andrewpaliga 

 need to add new gateway to shopify. 

Actually gateway has its own encryption technique. Gateway shares some keys with client(shop owner). Using this keys encryption is done on customers data  and encryted data is sent to gateway. Customer is redirected to gateways page where he fills payment information. Gateway performs the transaction shows transaction result successful or failed. Customer is again redirected to shop site.

  so it was suggested to use universal.rb or add gateway to offsite_payments. (using universal.rb i need to do major  changes at gateway side )

i need help for knowing certain things about offsite_payment:-

1. can we use gateway specific encryption technique  i.e which gateway prefers instead of creating signature hash  and sending.

2. while sending data to payment gateway page do we have to send signature hash  of fields and is it mandatory?

3. once transaction is complete and we get response from gateway. Do we catch that response , if we catch where we catch it and how.

4. would like to know if there is any documentation or resource which will help me  to understand and implement my gateway in offsite_payments 

please give your suggestions.

**Comment by andrewpaliga** [comment]
Hi @avenuestest, thanks for reaching us. Please take a look at our [Hosted Payment SDK](https://docs.shopify.com/hosted-payment-sdk). The SDK is based on the `universal.rb` gateway and is the recommended integration method going forward. I suggest you build a abstraction layers that converts the universal interface to the format your gateway requires if there are certain reasons you can't use the API as is. Keep in mind that the Hosted Payment SDK is newly released and in beta.
