### ISSUE TITLE
Customize a string sent to Valitor

### ISSUE THREAD

**Issue by baldurh** [activemerchant/offsite_payments#242]
Hello. I would like to customize a string sent to Valitor payment gateway.
Currently this is hard coded in the integration code.

My question is this: Can a field be added to the Shopify Admin payment settings page to add a custom string?

<img width="659" alt="image 2017-04-21 at 11 05 50 e h" src="https://cloud.githubusercontent.com/assets/1823617/25298769/b5673ab6-26e7-11e7-8396-1fb27847a358.png">

Would this have to be done by Shopify or does the integration code provide these field settings somehow?

The alternative would be to change this hard coded string to be in Icelandic because this integration is mainly used by Icelandic shops and everything else on their payment page is in Icelandic (even the payload parameter names) as you can see:

<img width="1185" alt="image 2017-04-21 at 11 14 53 e h" src="https://cloud.githubusercontent.com/assets/1823617/25298835/706168d2-26e8-11e7-9571-5f3262a4bff6.png">

The line which would have to be changed is the following:
https://github.com/activemerchant/offsite_payments/blob/master/lib/offsite_payments/integrations/valitor.rb#L29

**Comment by baldurh** [comment]
Oh I forgot to mention that this is the string of the link which appears after purchase which takes you back to your order or the shop. So even the current English version isn’t good enough.

**Comment by bdewater** [comment]
> The alternative would be to change this hard coded string to be in Icelandic

This would be the only feasible solution, or does Valitor have a default string on their side that they use if there isn't a `succes_text`/`SlodTokstAdGjaldfaeraTexti` sent? I can't find docs on this API.

**Comment by baldurh** [comment]
I'll find out.
How come this is the only feasible solution? The Shopify admin is already providing two fields for this integration. Why would they not be able to add a new optional field?

**Comment by baldurh** [comment]
OK so no one at Valitor is responding to my messages. I would be fine with just changing the hard coded string. That’s definitely better than the current one.

**Comment by baldurh** [comment]
See the string in action here:
![screen shot 2017-06-09 at 20 27 07](https://user-images.githubusercontent.com/1823617/27002699-5f7e326e-4dd7-11e7-9056-2162dc317691.png)


As you can see it really stands out as the only English text on the page. I feel it is really confusing for the user.

**Comment by baldurh** [comment]
Not relevant anymore
