### ISSUE TITLE
Release recent gem version

### ISSUE THREAD

**Issue by alexdunae** [activemerchant/offsite_payments#244]
Hi there -- thanks for maintaining the gem -- it really helps smooth out payment integrations.  It seems that Rubygems is still at 2.3.0 from 2016 ( https://rubygems.org/gems/offsite_payments ) while the repo is at 2.5.0.  Are there any plans to release the current and future versions to Rubygems?

**Comment by elfassy** [comment]
Yes, we'll release every version from now on. Cheers
https://rubygems.org/gems/offsite_payments/versions/2.5.0

**Comment by alexdunae** [comment]
Sweet - thanks!

**Comment by rafaelfranca** [comment]
2.4.0 was also release https://rubygems.org/gems/offsite_payments/versions/2.4.0
