### ISSUE TITLE
Skrill API url

### ISSUE THREAD

**Issue by Bishop** [activemerchant/offsite_payments#253]
>Dear Merchant,

>We have identified that you are continuing to use a legacy URL for your transaction processing via either the Skrill Quick Checkout API or Skrill Wallet Checkout API: http://www.moneybookers.com/app/payment.pl. 

>On 1 September 2017, only our current URL will remain valid: https://pay.skrill.com. Following this date, should you not update to the new URL, your processing will cease.

**Comment by Krystosterone** [comment]
closed through: https://github.com/activemerchant/offsite_payments/pull/259
